apiVersion: v1
kind: ConfigMap
metadata:
  name: orpheus-operator-recipes
data:
  debugging: |
    dummy:
      enabled: false
      image: "maikeee32e/euphrosyne-recipes:latest"
      entrypoint: "dummy"
      description: "Dummy recipe for debugging purposes."
    http-errors:
      enabled: true
      image: "maikeee32e/euphrosyne-recipes:latest"
      entrypoint: "http-errors"
      description: "Recipe for debugging alerts related to HTTP errors."
  actions: |
    jira:
      enabled: true
      image: "maikeee32e/euphrosyne-recipes:latest"
      entrypoint: "jira"
      description: "Recipe for creating a JIRA issue."
