apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: k8s-jobs
spec:
  entrypoint: rand-num
  templates:
  - name: rand-num
    resource:
      action: create
      # the job is regarded to be succeeded if it runs successfully for over 2 times
      # the job is regarded to be failed if it runs fail for over 1 times
      successCondition: status.succeeded > 2
      failureCondition: status.failed > 1
      setOwnerReference: true
      # completions: 3 means the job will be done 3 times
      # parallelism: 3 means 3 pods will be created and run at a same time 
      manifest: |
        apiVersion: batch/v1
        kind: Job
        metadata:
          generateName: rand-num-
        spec:
          completions: 3
          parallelism: 3
          template:
            metadata:
              name: rand
            spec:
              containers:
              - name: rand
                image: python:alpine3.6
                command: ["python", "-c", "import random; import time; print(random.randint(1, 1000)); time.sleep(10)"]
              restartPolicy: Never
    outputs:
      parameters:
      # set the metadata.name as value to "job-name"
      - name: job-name
        valueFrom:
          jsonPath: '{.metadata.name}'

