apiVersion: apps/v1
kind: Deployment
metadata:
  name: euphrosyne-reconciler-redis
  labels:
    app: orpheus-operator
    component: euphrosyne-reconciler-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orpheus-operator
      component: euphrosyne-reconciler-redis
  template:
    metadata:
      labels:
        app: orpheus-operator
        component: euphrosyne-reconciler-redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
