apiVersion: v1
kind: Service
metadata:
  name: euphrosyne-reconciler-redis
  labels:
    app: orpheus-operator
    component: euphrosyne-reconciler-redis
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 6379
  selector:
    app: orpheus-operator
    component: euphrosyne-reconciler-redis
