apiVersion: apps/v1
kind: Deployment
metadata:
  name: euphrosyne-reconciler
  labels:
    app: orpheus-operator
    component: euphrosyne-reconciler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orpheus-operator
      component: euphrosyne-reconciler
  template:
    metadata:
      labels:
        app: orpheus-operator
        component: euphrosyne-reconciler
    spec:
      containers:
        - name: euphrosyne-reconciler
          image: phoevos/euphrosyne-reconciler:latest
          command:
            - /reconciler
          args:
            - --webex-bot-address
            - https://eurydice-webex-bot.onrender.com
            - --redis-address
            - euphrosyne-reconciler-redis.default.svc.cluster.local:80
            - --recipe-timeout
            - "300"
          ports:
            - containerPort: 8080
      serviceAccountName: euphrosyne-reconciler
