apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: euphrosyne-reconciler
  name: euphrosyne-reconciler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: euphrosyne-reconciler
subjects:
- kind: ServiceAccount
  name: euphrosyne-reconciler
