apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: euphrosyne-reconciler
  name: euphrosyne-reconciler
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - create
  - deletecollection
