apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: orpheus-operator
    component: euphrosyne-reconciler
  name: euphrosyne-reconciler
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - create
  - deletecollection
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - get
  - list
  - create
  - deletecollection

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: orpheus-operator
    component: euphrosyne-reconciler
  name: euphrosyne-reconciler-recipes
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - deletecollection
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - get
  - list
  - create
  - deletecollection